var readline = require('readline-sync');
var givenMonth = readline.question("What month?");
var givenYear = readline.question("What year?");;
var d = new Date();
var months = ["January","February","March","April","May","June","July","August","September","October","November","December"];
var todayMonth = months[d.getMonth()];
var currentYear= d.getFullYear();
var currentMonthNumber = months.indexOf(todayMonth) + 1 ;
var monthDifference = currentMonthNumber - givenMonth;
var yearDifference = currentYear - givenYear;
console.log( "This is the difference between the given date and the current date: " + yearDifference + " years and " + Math.abs(monthDifference) + " months");
